# Generated by Django 6.0 on 2025-12-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
