# Generated by Django 6.0 on 2025-12-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpro', '0003_student_teacher_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='newpro.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpro.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpro.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpro.student')),
            ],
        ),
    ]
